name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: |
          export PREVIEW=true
          export PR_NUMBER=${{ github.event.number }}
          npm run build

      - name: Fetch all branches
        if: github.event_name == 'pull_request'
        run: git fetch --all

      - name: Create gh-pages branch if not exists
        if: github.event_name == 'pull_request'
        run: |
          git checkout gh-pages || git checkout -b gh-pages
          git pull origin gh-pages

      - name: Move build to preview directory
        if: github.event_name == 'pull_request'
        run: |
          rm -rf pr-${{ github.event.number }}
          mv dist pr-${{ github.event.number }}

      - name: Commit and push changes
        if: github.event_name == 'pull_request'
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add pr-${{ github.event.number }}
          git commit -m "Deploy preview for PR #${{ github.event.number }}"
          git push origin gh-pages

      - name: Log directory contents
        run: ls -la pr-${{ github.event.number }}
