name: Deploy Main to GitHub Pages

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out main branch
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        run: npm run build

      - name: Deploy to gh-pages
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git fetch origin gh-pages
          git switch gh-pages || git switch --orphan gh-pages
          ls -A | grep -v '.git' | xargs rm -rf
          cp -r dist/* .
          rm -rf dist
          git add .
          git commit -m "Deploy main branch to GitHub Pages" || echo "Nothing to commit"
          git push origin gh-pages --force
