name: Cleanup Preview after PR close

on:
  pull_request:
    types:
      - closed

permissions:
  contents: write

jobs:
  cleanup:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Fetch gh-pages
        run: |
          git fetch origin gh-pages
          git checkout gh-pages
          git pull origin gh-pages

      - name: Verify PR exists
        run: |
          if [ ! -d "pr-${{ github.event.number }}" ]; then
            echo "PR folder not found, skipping."
            exit 0
          fi

      - name: Remove preview folder
        run: |
          rm -rf pr-${{ github.event.number }}
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
          git add .
          git commit -m "Cleanup preview for PR #${{ github.event.number }}" || echo "Nothing to commit"
          git push origin gh-pages
