name: Deploy Preview to GitHub Pages

on:
  pull_request:
    types:
      - opened
      - synchronize
      - reopened

permissions:
  contents: write
  pull-requests: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Check out the repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build project
        env:
          PREVIEW: true
          PR_NUMBER: ${{ github.event.number }}
        run: |
          set -e
          npm run build

      - name: Save build output
        run: |
          set -e
          mv dist /tmp/pr-preview-build

      - name: Fetch gh-pages
        run: |
          set -e
          git fetch origin gh-pages
          git checkout gh-pages
          git pull origin gh-pages

      - name: Deploy Preview
        run: |
          set -e
          rm -rf pr-${{ github.event.number }}
          cp -R /tmp/pr-preview-build pr-${{ github.event.number }}
          touch pr-${{ github.event.number }}/.nojekyll

          echo "Listing preview directory contents:"
          ls -la pr-${{ github.event.number }}

          # Clean up any existing git state
          git reset

          # Configure git
          git config user.name "github-actions[bot]"
          git config user.email "41898282+github-actions[bot]@users.noreply.github.com"

          # Add all files in the preview directory
          echo "Adding files to git:"
          git add -A pr-${{ github.event.number }}

          echo "Git status:"
          git status

          # Commit and push
          if git status --porcelain | grep '^[MADRC]'; then
            git commit -m "Deploy preview for PR #${{ github.event.number }}"
            git push origin gh-pages
          else
            echo "No changes to commit"
          fi

      - name: Clean up node_modules
        run: |
          rm -rf node_modules
          if git ls-files --error-unmatch node_modules > /dev/null 2>&1; then
            git rm -r --cached node_modules
          fi

      - name: Post GitHub Comment with Preview URL
        uses: actions/github-script@v6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const prNumber = context.payload.number;
            const previewUrl = `https://lukmarcus.github.io/litera-po-literze/pr-${prNumber}/`;

            await github.rest.issues.createComment({
              issue_number: prNumber,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: `🚀 PR Preview deployed successfully! [Click here to view it](${previewUrl})`
            });
